controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout


